[font]
size = 9

[font.offset]
# x = -1
# y = 4

[font.bold]
family = "Monaspace Krypton Var"
style = "Bold"

[font.bold_italic]
family = "Monaspace Radon Var"
style = "Bold Italic"

[font.italic]
family = "Monaspace Radon Var"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
# family = "Monaspace Radon Var"
style = "light"

[window]
opacity = 0.9
blur = true
dimensions = { columns = 180, lines = 50 }
decorations = "None"

[cursor.style]
blinking = "On"

### Fonts

## JetBrains Mono Nerd Font
# style = "Bold" | "Regular" | "Italic"

## Monaspace Radon Var
# Monaspace Xenon Var
# Monaspace Argon Var
# Monaspace Neon Var
# Monaspace Krypton Var

